- name: Deploy Flask ML App using Docker and Kubernetes
  hosts: all
  become: yes

  vars:
    project_path: /home/ashu304/mechanical-ml-flask-project

  tasks:
    - name: Pull latest code (for k8s manifests)
      git:
        repo: https://github.com/ashu304-ops/ml-project.git
        dest: "{{ project_path }}"
        force: yes
    - name: Apply Kubernetes Deployment
      shell: /snap/bin/kubectl apply -f {{ project_path }}/k8s/deployment.yaml
      environment:
        KUBECONFIG: /home/ashu304/.kube/config

    - name: Apply Kubernetes Service
      shell: /snap/bin/kubectl apply -f {{ project_path }}/k8s/service.yaml
      environment:
        KUBECONFIG: /home/ashu304/.kube/config

